# Generated by Django 5.0.6 on 2024-08-21 05:02

import ckeditor.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave de Curso')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre del Curso')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio del Curso')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio del Curso')),
                ('fecha_termino', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Finalización del Curso')),
                ('horas', models.IntegerField(default=0, verbose_name='Total de Horas del Curso')),
                ('cupos', models.IntegerField(default=0, verbose_name='Limite de cupos')),
                ('cupos_restantes', models.IntegerField(default=0, verbose_name='Cupos Restantes')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia')),
                ('descripcion', models.TextField(default='', verbose_name='Descripcion General del Curso')),
                ('profesor', models.CharField(default='Por asignar', max_length=50)),
                ('contenido', ckeditor.fields.RichTextField(default='', verbose_name='Contenido')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Preinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('correo', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Preinscripción',
                'verbose_name_plural': 'Preinscripciones',
                'ordering': ['-created'],
            },
        ),
    ]
