# Generated by Django 5.0.6 on 2024-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='preinscripciones_count',
            field=models.IntegerField(default=0, verbose_name='Total de Preinscripciones'),
        ),
    ]
